/* Renders each downloadable PDF's first page as the thumbnail shown on its
   card in the Learn More section.
   ==================================================================
   The cards used to show an identical grey block with "PDF" on it, so the
   pair read as one document offered twice and neither told a visitor what
   they were about to download.

   Run after scripts/build-pdfs.mjs, which is what changes the covers:
     node scripts/build-pdfs.mjs && node scripts/build-covers.mjs

   Needs pdftoppm (poppler-utils) and cwebp, or ImageMagick. Deliberately not
   wired into `npm run build`: the PDFs are regenerated by hand when content
   changes, and the rendered covers are committed alongside them. */

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'public/images/downloads');

const DOCS = [
  ['IXAR-Company-Profile.pdf', 'cover-profile.webp'],
  ['IXAR-Africa-Project-List.pdf', 'cover-projects.webp'],
];

fs.mkdirSync(OUT, { recursive: true });
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'ixar-covers-'));

for (const [pdf, webp] of DOCS) {
  const src = path.join(ROOT, 'public/downloads', pdf);
  if (!fs.existsSync(src)) {
    console.error(`  missing ${pdf} — run scripts/build-pdfs.mjs first`);
    process.exitCode = 1;
    continue;
  }
  const stem = path.join(tmp, webp.replace('.webp', ''));
  execFileSync('pdftoppm', ['-png', '-r', '150', '-f', '1', '-l', '1', src, stem]);
  const png = fs.readdirSync(tmp).find((f) => f.startsWith(path.basename(stem)) && f.endsWith('.png'));
  execFileSync('cwebp', ['-q', '88', '-resize', '760', '0', path.join(tmp, png), '-o', path.join(OUT, webp)]);
  console.log(`  ${webp}  ${(fs.statSync(path.join(OUT, webp)).size / 1024).toFixed(0)} kB`);
}

fs.rmSync(tmp, { recursive: true, force: true });
